common: &common
  adapter: postgresql
  username: momentum
  password: momentum-password # from psql setup, see Postgresql

development:
  <<: *common
  database: angular_momentum_db

test:
  <<: *common
  database: angular_momentum_db

production:
  <<: *common
  database: angular_momentum_db